version: '3.5'

services:
  api:
    container_name: go-httpenv
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./main" ]
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - go-httpenv
    restart: always

networks:
  go-httpenv:
    driver: bridge
